/* eslint-disable prettier/prettier */
import { BaseEntity, Entity, PrimaryGeneratedColumn, Column, ManyToOne } from 'typeorm';
import { TaskStatus } from './helpers/task-status.enum';
import { User } from 'src/auth/user.entity';

// defining the Task entity with the parameters id, title, description and status
@Entity()
export class Task extends BaseEntity {
  // id is the auto generated primary key
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  description: string;

  @Column()
  status: TaskStatus;

  @ManyToOne(type => User, user => user.tasks, { eager: false })
  user: User;

  @Column()
  userId: number; // auto generated by typeorm
}